METHOD_CATALOG = [
 ('ph_potentiometric','potentiometric pH','acid_base','pH determined potentiometrically in specified extractant'),
 ('soc_tyurin','Tyurin wet oxidation','organic','organic carbon by Tyurin method'),
 ('soc_walkley_black','Walkley-Black wet oxidation','organic','organic carbon by dichromate oxidation'),
 ('soc_dry_combustion','dry combustion elemental analysis','organic','carbon/nitrogen by elemental analyser'),
 ('nitrogen_kjeldahl','Kjeldahl digestion','macronutrient','total nitrogen by Kjeldahl'),
 ('nitrogen_dumas','Dumas combustion','macronutrient','total nitrogen by combustion'),
 ('phosphorus_olsen','Olsen extraction','macronutrient','bicarbonate-extractable phosphorus'),
 ('phosphorus_bray','Bray extraction','macronutrient','fluoride-acid extractable phosphorus'),
 ('mehlich_3','Mehlich-3 extraction','macronutrient','multi-element Mehlich-3 extraction'),
 ('chirikov','Chirikov extraction','macronutrient','acid extract for mobile P and K'),
 ('machigin','Machigin extraction','macronutrient','carbonate extract for mobile P and K'),
 ('cec_ammonium_acetate','ammonium acetate CEC','exchange','cation exchange capacity by NH4OAc'),
 ('particle_pipette','pipette particle-size analysis','particle_size','sedimentation/pipette method'),
 ('particle_laser','laser diffraction particle-size analysis','particle_size','laser diffraction'),
 ('metals_aas','atomic absorption spectrometry','trace_elements','AAS'),
 ('metals_icp_oes','ICP-OES','trace_elements','inductively coupled plasma optical emission spectrometry'),
 ('metals_icp_ms','ICP-MS','trace_elements','inductively coupled plasma mass spectrometry'),
 ('xrf','X-ray fluorescence','geochemical','XRF'),
 ('loss_on_ignition','loss on ignition','organic','LOI'),
]
